root_dir: .
api_dir: apis
static_dir: static
static_route_prefix: /
port: 3000
silent:
error_log_file_path: ./error.log
log_size: 10M
debug_log_file_path: ./debug.log
watch:
plugins:
  swagger:
    path: /swagger
    documentation:
      title: "Test"
rewrites:
  - path: ''
    test: ^(index)$ # rewrite index for ''
