name: Builder
on:
  push:
    # Sequence of patterns matched against refs/tags
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        uses: oven-sh/setup-bun@v2
        run: bun install --frozen-lockfile && bun run build:all
        with:
          bun-version: latest

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          overwrite: true
          tags: true
          tag: ${{ github.ref }}
